Repository g3w-suite/g3w-client-plugin-editing, pull requests merged in 2024-01, with the labels that each got.

#33 Toolbox get origname of layer instead of name
  toolboxes/toolboxesfactory.js
Labels: feature

#83 Add support for chain filter option within relation reference widget
  components/Toolbox.vue
  eventbus.js
  form/editingform.js
  services/editingservice.js
  workflows/steps/tasks/openformtask.js
Labels: feature

#80 Handle deep relations
  api/index.js
  components/Editing.vue
  components/FormRelation.vue
  components/SaveAll.vue
  components/Toolbox.vue
  form/editingform.js
  form/editingformservice.js
  index.js
  services/editingservice.js
  services/relationservice.js
  toolboxes/tool.js
  toolboxes/toolbox.js
  toolboxes/toolboxesfactory.js
  utils/cloneFeature.js
  workflows/steps/tasks/confirmtask.js
  workflows/steps/tasks/deletefeaturetask.js
  workflows/steps/tasks/editingtask.js
  workflows/steps/tasks/openformtask.js
Labels: feature

#65 Include files from core (ref: `g3wsdk.core.editing`)
  g3wsdk/changesmanager.js
  g3wsdk/editor.js
  g3wsdk/history.js
  g3wsdk/index.js
  g3wsdk/session.js
  g3wsdk/sessionsregistry.js
  index.js
Labels: refactoring

#89 Missing cloneFeature method
  workflows/steps/tasks/moveelementstask.js
  workflows/steps/tasks/openformtask.js
Labels: bug

#91 Highlight selected features when using the following tools: "Copy features", "Add part to multipart", "Split Feature"
  workflows/steps/tasks/addfeaturetask.js
  workflows/steps/tasks/editingtask.js
  workflows/steps/tasks/getvertextask.js
  workflows/steps/tasks/moveelementstask.js
  workflows/steps/tasks/movefeaturettask.js
  workflows/steps/tasks/splitfeaturetask.js
Labels: ux

#92 Backport PR #89: missing cloneFeature method
  workflows/steps/tasks/addfeaturetask.js
  workflows/steps/tasks/editingtask.js
  workflows/steps/tasks/getvertextask.js
  workflows/steps/tasks/moveelementstask.js
  workflows/steps/tasks/movefeaturettask.js
  workflows/steps/tasks/openformtask.js
  workflows/steps/tasks/splitfeaturetask.js
Labels: bug

#94 Get Layer title and not origin name, name for editing toolbox title layer
  toolboxes/toolboxesfactory.js
Labels: bug
