Repository g3w-suite/g3w-client-plugin-editing, pull requests merged in 2025-01, with the labels that each got.

#141 Add close form button on deep relations form
  components/Toolbox.vue
  g3wsdk/editing/editor.js
  g3wsdk/workflow/step.js
  g3wsdk/workflow/workflow.js
  toolboxes/toolbox.js
  utils/dissolve.js
  utils/handleRelation1_1LayerFields.js
  utils/listenRelation1_1FieldChange.js
  workflows/index.js
Labels: feature

#142 🐛 Handle join 1:1 relation fields and handle 3D geometry feature type
  toolboxes/toolbox.js
  utils/handleRelation1_1LayerFields.js
  utils/listenRelation1_1FieldChange.js
  workflows/index.js
Labels: bug

#145 Remove lodash + make use of native ES6 modules
  components/CopyFeaturesFromOtherLayers.vue
  components/Toolbox.vue
  g3wsdk/workflow/workflow.js
  index.js
  toolboxes/toolbox.js
  utils/areCoordinatesEqual.js
  utils/chooseFeatureFromFeatures.js
  utils/isPointOnVertex.js
  workflows/index.js
Labels: refactoring
